server:
  port: 9003

spring:
  application:
    name: member-service
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mysql://141.164.61.114:3306/temeethb?serverTimezone=UTC&characterEncoding=UTF-8
    username: lntemeetuser
    password: Temeet2580!@#$

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true


eureka :
  instance:
    hostname: 141.164.61.114
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin2580@${eureka.instance.hostname}:9000/eureka/